name: "tca8418"
version: "0.2.0"
esphome:
  min_version: 2024.6.0
dependencies:
  - i2c

components:
  - id: tca8418
    class: esphome::tca8418::TCA8418Component
    arguments: ["esphome::i2c::I2CDevice"]
    base: ["Component"]

pins:
  tca8418:
    class: esphome::tca8418::TCA8418GPIOPin
    hub: esphome::tca8418::TCA8418Component
    schema:
      tca8418: { required: true, id: true }
      number: { required: true, type: int }
